
<ul>
<li> <a href="01intro.php"> Kevin A. Delorey</a></li>
<li style="padding-left: 20px"> 
     <a href="02contact.php"> Contact Me</a></li>
<li style="padding-left: 20px">
     <a href="03qualifications.php"> Qualifications</a></li>
<li> <a href="04CPM.php">Construction Project Management</a></li>
<li style="padding-left: 20px">
     <a href="05difference.php">My Specialty</a></li>
<li style="padding-left: 20px">
     <a href="06forms.php">Multi-Party Documents</a></li>
<li> <a href="07projects.php">Projects</a></li>
<li style="padding-left: 20px">
    <a href="08customization.php">Tailored Services</a></li>
<li style="padding-left: 20px">
    <a href="09telecommuting.php">Consultations</a></li>
<li style="padding-left: 20px">
    <a href="10partners.php">Partnering With</a></li>
<li> Best Practice: "definition"</li>
<li style="padding-left: 20px">
    <a href="11lessons.php">Lessons Learned</a></li>
<li style="padding-left: 20px">
    <a href="12mistakes.php">Most Common Mistakes</a></li>
<li style="padding-left: 20px">
    <a href="13resources.php">Free Resources</a></li>
<li> Get More Info</li>
<li  style="padding-left: 20px"</li> 
    <a href="14moreinfo.php">What Are My Risks?</a></li>
<li  style="padding-left: 20px"> 
    <a href="15begin.php">Let's Get Started</a></li>
<ul/>
