
<table border="0px">
            <tr>
                <td><img src="map.jpg"height=150 width=150 
                    style="padding:10px 80px 10px 85px"</td> 
                <td><img src="map.jpg"height=150 width=150 
                    style="padding:10px 80px 10px 85px"</td> 
                <td><img src="map.jpg"height=150 width=150 
                    style="padding:10px 80px 10px 85px"</td> 
            </tr>
            <tr>
                <td>Construction Management</td> 
                <td>Kevin A. Delorey</td>
                <td>Best Practice</td>
            </tr>
        </table>
